/* State and persistence: validate untrusted or outdated saved configurations. */
const STORAGE_KEY='nymeria.character.v1';
const DEFAULT_STATE={hair:'veil',hairColor:'ink',eyes:'amber',torso:'warden',legs:'ranger',boots:'plate',cloak:'dusk',weapon:'sword',dye:'sea'};
const ALLOWED={...Object.fromEntries(Object.entries(ITEMS).map(([k,v])=>[k,v.map(x=>x.id)])),hairColor:PALETTES.hair.map(x=>x.id),eyes:PALETTES.eyes.map(x=>x.id),dye:PALETTES.dye.map(x=>x.id)};
function validateState(candidate){return Object.fromEntries(Object.entries(DEFAULT_STATE).map(([k,v])=>[k,ALLOWED[k].includes(candidate?.[k])?candidate[k]:v]));}
let state={...DEFAULT_STATE},storageUnavailable=false;
try{state=validateState(JSON.parse(localStorage.getItem(STORAGE_KEY)));}catch{storageUnavailable=true;}
let category='appearance';
const CATEGORIES={appearance:'Aspetto',torso:'Corazza',legs:'Gambe',boots:'Stivali',cloak:'Mantello',weapon:'Arma',dye:'Tintura'};
const findItem=(slot)=>ITEMS[slot].find(x=>x.id===state[slot]);
const color=(palette,id)=>PALETTES[palette].find(x=>x.id===id).color;
const rig=document.querySelector('#rig');
/* Persistent groups form the rig. Equip updates only the affected group's children. */
for(const layer of LAYER_ORDER){const g=document.createElementNS('http://www.w3.org/2000/svg','g');g.dataset.layer=layer;g.classList.add('layer');rig.append(g);}
function renderLayer(layer){const group=[...rig.children].find(g=>g.dataset.layer===layer);let markup=ANATOMY[layer];if(layer==='hair-back')markup=findItem('hair').back;else if(layer==='hair-front')markup=findItem('hair').front;else if(layer==='eyes')markup='<path fill="none" stroke="#503e3c" d="M131 94L142 92M158 92L169 94"/><path fill="#eee5d3" stroke="none" d="M132 98Q137 94 142 98Q137 101 132 98ZM158 98Q163 94 168 98Q163 101 158 98Z"/><path fill="var(--eyes)" stroke="#233b3d" stroke-width=".8" d="M136 95H139V100H136ZM161 95H164V100H161Z"/>';else if(ITEMS[layer])markup=findItem(layer).svg;group.innerHTML=markup;group.dataset.item=layer.startsWith('hair-')?state.hair:state[layer]||'base';}
function applyColors(){rig.style.setProperty('--hair',color('hair',state.hairColor));rig.style.setProperty('--eyes',color('eyes',state.eyes));[...rig.children].find(g=>g.dataset.layer==='torso').style.setProperty('--dye',color('dye',state.dye));}
function stats(){const values={force:12,dexterity:15,vitality:14,spirit:11};for(const slot of ['torso','weapon'])for(const [k,v] of Object.entries(findItem(slot).stats))values[k]+=v;document.querySelector('#power').textContent=Object.values(values).reduce((a,b)=>a+b,0)+18;document.querySelector('#stats').innerHTML=Object.entries(values).map(([k,v])=>`<div><dt>${{force:'Forza',dexterity:'Agilità',vitality:'Vigore',spirit:'Spirito'}[k]}</dt><dd>${v}</dd></div>`).join('');}
function equip(key,id){if(!ALLOWED[key]?.includes(id))return;state[key]=id;if(key==='hair'){renderLayer('hair-back');renderLayer('hair-front');}else if(ITEMS[key])renderLayer(key);applyColors();stats();renderOptions();}
/* UI uses item data, never geometry selectors to infer state. */
function swatches(key,palette){return `<div class="swatches">${PALETTES[palette].map(x=>`<button class="swatch" style="--swatch:${x.color}" data-key="${key}" data-id="${x.id}" aria-label="${x.name}" title="${x.name}" aria-pressed="${state[key]===x.id}"></button>`).join('')}</div>`;}
function itemGrid(slot){return `<div class="item-grid">${ITEMS[slot].map(x=>`<button class="item" data-key="${slot}" data-id="${x.id}" aria-pressed="${state[slot]===x.id}"><svg viewBox="${{hair:'105 50 90 90',torso:'95 132 108 160',legs:'110 218 80 125',boots:'95 300 110 90',cloak:'90 130 120 230',weapon:'195 78 60 310'}[slot]}" aria-hidden="true" style="--hair:${color('hair',state.hairColor)};--dye:${color('dye',state.dye)}"><g class="layer">${slot==='hair'?x.back+x.front:x.svg}</g></svg><span><strong>${x.name}</strong><small>${x.detail}</small></span></button>`).join('')}</div>`;}
function renderOptions(){const options=document.querySelector('#options');if(category==='appearance')options.innerHTML='<p class="option-label">SILHOUETTE CAPELLI</p>'+itemGrid('hair')+'<p class="option-label">COLORE CAPELLI</p>'+swatches('hairColor','hair')+'<p class="option-label">COLORE OCCHI</p>'+swatches('eyes','eyes');else if(category==='dye')options.innerHTML='<p class="option-label">TINTURA DELLA CORAZZA</p>'+swatches('dye','dye')+'<p class="hint">Il pigmento cambia soltanto gli inserti della corazza. Metallo, pelle e altri slot mantengono il proprio materiale.</p>';else options.innerHTML=itemGrid(category);}
function selectCategory(next){category=next;document.querySelector('#selection-label').textContent=CATEGORIES[category];document.querySelectorAll('#categories button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.category===category)));document.querySelectorAll('.equipment button').forEach(b=>b.classList.toggle('active',b.dataset.category===category));renderOptions();}
document.querySelector('#categories').innerHTML=Object.entries(CATEGORIES).map(([id,label])=>`<button data-category="${id}" aria-pressed="${id===category}">${label}</button>`).join('');
const right=document.createElement('nav');right.className='equipment right';right.setAttribute('aria-label','Slot destri');right.innerHTML='<button data-category="cloak" aria-label="Mantello">◬<small>04</small></button><button data-category="weapon" aria-label="Arma">†<small>05</small></button><button data-category="appearance" aria-label="Aspetto">✧<small>06</small></button>';document.querySelector('.stage').append(right);
document.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;if(button.dataset.category)selectCategory(button.dataset.category);if(button.dataset.key)equip(button.dataset.key,button.dataset.id);});
let noticeTimer;function notify(text){const n=document.querySelector('#notice');n.textContent=text;n.classList.add('show');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>n.classList.remove('show'),2600);}
document.querySelector('#random').addEventListener('click',()=>{for(const [key,values] of Object.entries(ALLOWED))state[key]=values[Math.floor(Math.random()*values.length)];LAYER_ORDER.forEach(renderLayer);applyColors();stats();renderOptions();notify('Un nuovo volto delle soglie');});
document.querySelector('#save').addEventListener('click',()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));notify('Aspetto salvato su questo dispositivo');}catch{notify('Salvataggio non disponibile in questo browser');}});
LAYER_ORDER.forEach(renderLayer);applyColors();stats();renderOptions();if(storageUnavailable)notify('Memoria locale non disponibile o dati non validi');
