/* Activity durations, encounters, rewards and events are all tunable here. */
const ExpeditionData = (() => {
  const activities = [
    {
      id: "patrol",
      name: "Pattuglia delle Rovine",
      durationMs: 60000,
      requiredLevel: 1,
      encounters: 3,
      difficulty: 1,
      enemy: { hp: 0.32, damage: 0.5, armor: 0.5 },
      rest: 0.4,
      eventChance: 0.35,
      xpPerEncounter: 18,
      completionXP: 36,
      crownsPerEncounter: 4,
      completionCrowns: 8,
      materialQuantity: 1,
      lootChance: 0.12,
      finalLootChance: 0.3,
      lootTable: ["frontier-ring", "moon-boots"],
    },
    {
      id: "broken-trail",
      name: "Sentiero Spezzato",
      durationMs: 300000,
      requiredLevel: 3,
      encounters: 5,
      difficulty: 2,
      enemy: { hp: 0.75, damage: 0.75, armor: 0.8 },
      rest: 0.4,
      eventChance: 0.4,
      xpPerEncounter: 30,
      completionXP: 50,
      crownsPerEncounter: 6,
      completionCrowns: 15,
      materialQuantity: 2,
      lootChance: 0.14,
      finalLootChance: 0.35,
      lootTable: ["frontier-ring", "moon-boots", "vesper-blade"],
    },
    {
      id: "recon",
      name: "Ricognizione del Vespro",
      durationMs: 900000,
      requiredLevel: 5,
      encounters: 8,
      difficulty: 3,
      enemy: { hp: 1, damage: 1, armor: 1.1 },
      rest: 0.4,
      eventChance: 0.45,
      xpPerEncounter: 45,
      completionXP: 120,
      crownsPerEncounter: 9,
      completionCrowns: 24,
      materialQuantity: 3,
      lootChance: 0.16,
      finalLootChance: 0.4,
      lootTable: ["vesper-blade", "lunar-bow", "frontier-mail"],
    },
    {
      id: "vigil",
      name: "Veglia della Frontiera",
      durationMs: 1800000,
      requiredLevel: 8,
      encounters: 15,
      difficulty: 4,
      enemy: { hp: 1.5, damage: 1.35, armor: 1.4 },
      rest: 0.4,
      eventChance: 0.5,
      xpPerEncounter: 60,
      completionXP: 240,
      crownsPerEncounter: 12,
      completionCrowns: 40,
      materialQuantity: 4,
      lootChance: 0.18,
      finalLootChance: 0.45,
      lootTable: ["lunar-bow", "frontier-mail", "ether-quiver"],
    },
  ];
  const events = [
    {
      id: "merchant",
      name: "Mercante dei guadi",
      description: "Una consegna recuperata frutta Corone.",
      crowns: 7,
    },
    {
      id: "altar",
      name: "Altare del Vespro",
      description: "Le iscrizioni rendono più istruttivo questo incontro.",
      xpMultiplier: 1.2,
    },
    {
      id: "hidden-path",
      name: "Varco tra le spine",
      description:
        "Un passaggio rivela Fibra Lunare e aumenta la possibilità di trovare un oggetto.",
      materials: { fiber: 2 },
      lootBonus: 0.2,
    },
    {
      id: "ambush",
      name: "Imboscata dei cenerei",
      description:
        "Un incontro aggiuntivo, più difficile, segue quello previsto.",
      extraEncounter: true,
      difficultyMultiplier: 1.2,
    },
    {
      id: "ancient-ruin",
      name: "Archivio sepolto",
      description: "Polvere d’Etere e conoscenze dimenticate.",
      materials: { ether: 2 },
      xpMultiplier: 1.1,
    },
    {
      id: "wounded-creature",
      name: "Bestia ferita",
      description:
        "Aiutarla svela Ferro del Vespro e un percorso meno pericoloso.",
      materials: { iron: 2 },
      difficultyMultiplier: 0.85,
    },
  ];
  return {
    activities,
    events,
    location: "Frontiera del Vespro",
    maxEncounterSeconds: 180,
    previewSeeds: [11, 29, 71],
    activity: (id) => activities.find((a) => a.id === id),
  };
})();
if (typeof module !== "undefined" && module.exports)
  module.exports = ExpeditionData;
